### ISSUE TITLE
TM:PE PR 1233 breaks AR

### ISSUE THREAD

**Issue by originalfoo** [kianzarrin/AdvancedRoads#10]
https://github.com/CitiesSkylinesMods/TMPE/pull/1233

![image](https://user-images.githubusercontent.com/1386719/146049220-0d71c100-6c63-4924-9c4f-5b879b72c47f.png)

```
AdaptiveRoads.Patches.TMPE.OnSegmentFlagsChanged failed. [System.Exception]

Details:
HarmonyLib.HarmonyException: Patching exception in method System.Void TrafficManager.Manager.Impl.SpeedLimitManager::SetLaneSpeedLimit(System.UInt32 laneId, TrafficManager.State.SetSpeedLimitAction action) ---> System.Exception: Parameter "segmentId" not found in method System.Void TrafficManager.Manager.Impl.SpeedLimitManager::SetLaneSpeedLimit(System.UInt32 laneId, TrafficManager.State.SetSpeedLimitAction action)
  at HarmonyLib.MethodPatcher.EmitCallParameter (System.Reflection.MethodInfo patch, System.Collections.Generic.Dictionary`2 variables, Boolean allowFirsParamPassthrough, System.Reflection.Emit.LocalBuilder
```

**Comment by kvakvs** [comment]
That is not a member of any abstract interface, so I didn't bother to keep its function signature intact.
@kianzarrin An external API must have an interface for it. Where should this be added?

**Comment by kianzarrin** [comment]
I already fixed this before that PR was commited. I just need to publish the fix.

**Comment by kianzarrin** [comment]
@kvakvs this patch will be irrelevant soon so don't worry. 
I will switch to TMPE notifier once TMPE stable supports its
