### ISSUE TITLE
Custom flag names must be manually entered for Every. Single. Lane. and Elevation.

### ISSUE THREAD

**Issue by Elesbaan70** [kianzarrin/AdvancedRoads#13]
There really needs to be a way to copy custom flag names across lanes and elevations. I have shelved a project I'd already spent a fair amount of time on, because the process of entering these names is so time-consuming and error-prone that it made the whole thing unviable. This limitation is a severe enough usability issue to prevent me from creating assets that support AN.

**Comment by kianzarrin** [comment]
you can write a modtools script.
or maybe I can provide a button in the settings.

**Comment by kianzarrin** [comment]
fixed
