### ISSUE TITLE
Props -> Copy to other elevations does not work

### ISSUE THREAD

**Issue by Elesbaan70** [kianzarrin/AdvancedRoads#15]
### Steps to reproduce:

1. Create a new road asset using a vanilla road as a template. (It's best to use a road that does not render tunnels.)
2. On the ground elevation, select a vehicle lane.
3. Expand the props list.
4. Right-click any prop and click "Copy to other elevations".
5. Select the corresponding vehicle lane in the tunnel elevation.
6. Expand the props list.

The tunnel should have picked up the prop, but it's not there.

### Root cause:

Here the copy logic makes sure the source lane contains the prop being copied:
https://github.com/kianzarrin/AdaptiveNetworks/blob/1914b7fa40fa3e24ab8f1758e33b9c6dd26a322f/AdaptiveRoads/Util/PropHelpers.cs#L224

But that will never happen, because here the caller is providing a clone of the lane's prop:
https://github.com/kianzarrin/AdaptiveNetworks/blob/1914b7fa40fa3e24ab8f1758e33b9c6dd26a322f/AdaptiveRoads/Util/RoadEditorUtils.cs#L303-L304

### Remarks

I don't know enough about what the code is doing to be confident fixing this. I would probably break something else.

**Comment by Elesbaan70** [comment]
I may change the "copy to other elevation" and clipboard operations to leverage the revised template mechanism, in which case this issue would just go away. Can't say for sure yet, but that's one possibility.

**Comment by kianzarrin** [comment]
fixed
