### ISSUE TITLE
Stutter Every 15 seconds

### ISSUE THREAD

**Issue by ashleytayles** [kianzarrin/AdvancedRoads#17]
With both this and the stable branch I get some pretty bad performance issues on a small city of 1500.

I did extensive testing by removing all mods that weren't required for load and then added and subtracted mods to find this one being the cause. Here's the notes I took. If there's any outputs you want me to grab let me know.

By performance issues I mean every 15 seconds or so the game stutters. Very noticeable when moving the camera around or watching traffic.

CPU Ryzen 7 5800X
Radeon 5700XT
64gb RAM

By "all mods" I refer to this collection: https://steamcommunity.com/sharedfiles/filedetails/?id=2712368474

Required to load save:

81 tiles
more CitizenUnits
more PathUnits
Harmony 2.0.4-4 (Mod Dependency)
Loading screen mod

1st round: ### FINE ####
FPS Booster
Patch Loader Mod

2nd round	#### FIRST LAG PRESENT ####
TM:PE TEST 	
Hide Crosswalks V3.0 [EXPERIMENTAL]
Adaptive Networks (AN) V3.2.16 [Stable]

3rd round #### FINE ###
-- TM:PE TEST 					
-- Hide Crosswalks V3.0 [EXPERIMENTAL]
-- Adaptive Networks (AN) V3.2.16 [Stable]
ALL MODS EXCEPT ABOVE

4th Round #### FINE ####
All mod
++ TMPE TEST

5th Road ## LAG #####
++ Adaptive Networks (AN) V3.2.16 [Stable]

6th round ##### FINE ##
-- Adaptive Networks (AN) V3.2.16 [Stable]
disabled ++ Adaptive Networks (AN) 3.2.18-ALPHA

7th round ##### FINE ######
++ Hide Crosswalks V3.0 [EXPERIMENTAL]

7th round ###### LAG ###
enable ++ Adaptive Networks (AN) 3.2.18-ALPHA

8th round ### FINE ##
-- Adaptive Networks (AN) 3.2.18-ALPHA

**Comment by kianzarrin** [comment]
I can't reproduce this with minimal mod set and FPS booster

**Comment by chameleon-tbn** [comment]
How you disabled mods?

**Comment by kianzarrin** [comment]
can't reproduce
