### ISSUE TITLE
Need a node flag to indicate presence of pedestrian lanes

### ISSUE THREAD

**Issue by Elesbaan70** [kianzarrin/AdvancedRoads#18]
TM:PE will report that it allows pedestrian crossings even when there are no pedestrian lanes entering a node. This limits the usefulness of the ZebraCrossing flag for highway ramps that cross local streets, since crossings that depend on it will also be rendered on highway junctions.

One possible solution is to require that the asset creator write an expression to check for pedestrian lanes. But since this limitation directly impacts the usability of an existing feature, I suggest that it is better for AN to provide a node flag that does this work.

**Comment by Elesbaan70** [comment]
A more detailed description of the issue this addresses can be found at CitiesSkylinesMods/TMPE#1302

**Comment by kianzarrin** [comment]
fixed in TMPE
