### ISSUE TITLE
Upcoming changes to TM:PE mod options screen

### ISSUE THREAD

**Issue by originalfoo** [kianzarrin/AdvancedRoads#20]
(apologies for copy paste issue text)

Hi, not sure if this will affect your mod, but there are about to be major changes to **TM:PE mod options screen** - UI components, class structure, etc.

If that is likely to affect your mod, please let me know and we'll delay those updates until solution can be found. An API is already in PR review to allow external mods to reliably read mod options. For breif summary of the planned changes, see https://github.com/CitiesSkylinesMods/TMPE/issues/1356

**Comment by chameleon-tbn** [comment]
Thanks for Info @aubergine10 ... I Hope @kianzarrin will read this soon. A few dass ago He was Not healthy and now already a few days i was Not able to reach him...

**Comment by originalfoo** [comment]
I hope he's ok. Get well soon Kian!

**Comment by originalfoo** [comment]
FYI: First batch of changes to TM:PE mod options will be in TM:PE 11.6.5.0 TEST release.

**Comment by kianzarrin** [comment]
if it is only adding API and not removing any API it should be fine.

**Comment by kianzarrin** [comment]
In any case I don't access TMPE options in any of my mods so it should be fine.
