### ISSUE TITLE
All roads are blue in Asset Editor when using Adaptive Networks

### ISSUE THREAD

**Issue by ghost** [kianzarrin/AdvancedRoads#23]
So a few days ago I was working on a custom road network in the asset editor, and suddenly after I rebooted the game one time I went back into the asset editor and one of the six lane roads (I forget which one specifically) was blue and error appeared when I placed it. Then after some general troubleshooting steps and a few game reboots all the roads I placed in the asset editor were blue and made errors appear. And the blue roads & error only happens in the asset editor not in any saves or scenarios.

This is what the blue roads looked like:
![Screenshot 2022-09-18 063831](https://user-images.githubusercontent.com/43016543/190897942-e6045015-a3f3-42b5-856f-cc2ead2873e0.png)
And the error:
![Screenshot 2022-09-18 065606](https://user-images.githubusercontent.com/43016543/190898660-aed8acd7-5d40-40e9-8d25-d0ec1e432705.png)

(FYI this was already a few days after the Plazas & Promenades update so everything I was using had been updated and compatible with the update and each other)
The only mods I had installed at the time when using the asset editor were the following:
- Adaptive Networks [Stable]
- [Harmony 2](https://steamcommunity.com/sharedfiles/filedetails/?id=2040656402)
- [TM:PE [Stable]](https://steamcommunity.com/sharedfiles/filedetails/?id=1637663252)
- [Network Dump Tools](https://steamcommunity.com/sharedfiles/filedetails/?id=1845697704)
- [ACME](https://steamcommunity.com/sharedfiles/filedetails/?id=2778750497)
- [Network Extensions 2](https://steamcommunity.com/sharedfiles/filedetails/?id=812125426)
- [Loading Order Mod](https://steamcommunity.com/sharedfiles/filedetails/?id=2448824112)
- [Patch Loader Mod](https://steamcommunity.com/workshop/filedetails/?id=2041457644)
As well as some custom assets from the workshop and locally.

After removing each mod one by one (also removed all custom assets & other content) I narrowed it down to this mod. With the only custom content installed being this mod, and the two dependencies required (Harmony & TM:PE), there are blue roads/error in asset editor. And when I remove only this mod and leave the two dependencies installed it no longer occurs.

I've tried all the fixes I can think of and have found when searching about this issue: verifying game files, uninstalling & reinstalling all workshop content, restarting PC, changing order in loading order mod, and more. I'm going to try clean reinstalling the entire game now and hope it fixes the issue (will update here when that is complete) but I'm still posting this bug report now because it seems pretty game breaking, I've spent at least 12 hours in the past few days trying to troubleshoot this issue since the problem first occurred and I have absolutely no idea what I did that could have caused this.

Here are the exact steps I did for the 2 logs attached below (With the only custom content installed being this mod and the two dependencies):
Play via Steam library > Play in Paradox launcher that pops up
Once loaded, in main menu...
Editors > Asset editor > New
Once loaded, in asset importer menu...
Select "Road" category > Select "Six-Lane Road with Median" > Place that road down via the "Roads" button in the toolbar (not the "Place your custom road" button) > Road was blue and immediately an Error box pops up (as shown in the screenshots earlier) > After clicking "Ok" in the error box it will instantly reappear 1-4 more times > Quit to desktop.
(I used "Six-Lane Road with Median" in this example but it doesn't matter what road you select, the same issue is present with all of them; it also doesn't matter whether you use the "Road" or "Place your custom road" button the same issue happens with both as well) 

### Logs from doing the exact steps stated above:
[AdaptiveRoads.log](https://github.com/kianzarrin/AdaptiveNetworks/files/9611049/AdaptiveRoads.log)
[output_log.txt](https://github.com/kianzarrin/AdaptiveNetworks/files/9611050/output_log.txt)

EDIT: also logs when using debug mode:
[AdaptiveRoads.log](https://github.com/kianzarrin/AdaptiveNetworks/files/9611309/AdaptiveRoads.log)
[output_log.txt](https://github.com/kianzarrin/AdaptiveNetworks/files/9611313/output_log.txt)

**Comment by ghost** [comment]
Update: After a clean reinstall (I uninstalled all custom content, the game, and deleted all the game files I could find in File Explorer) the blue roads and error STILL HAPPENS, please can someone help fix this issue.

**Comment by kianzarrin** [comment]
nothing special in the log. and I don't get blue roads like you. I wonder whats going on.

**Comment by ghost** [comment]
> nothing special in the log. and I don't get blue roads like you. I wonder whats going on.

Yea its so weird, Is there anything I could have done accidently in the asset editor that would have caused the problem or for something to break?

**Comment by kianzarrin** [comment]
fixed in V3.13.2
